/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import javax.swing.JOptionPane;

/**
 *
 * @author Ronny Trinidad
 */
public class Create extends javax.swing.JFrame {

    /**
     * Creates new form Create
     */
    public Create() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        btn_basic = new javax.swing.JButton();
        btn_advanced = new javax.swing.JButton();
        lbl_basic = new javax.swing.JLabel();
        lbl_advanced = new javax.swing.JLabel();
        btn_back = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Book Antiqua", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Crear Curriculum");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 410, 74));
        getContentPane().add(Separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 110, 550, 10));

        jPanel1.setBackground(new java.awt.Color(1, 0, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_basic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CBasic.jpg"))); // NOI18N
        btn_basic.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btn_basic.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        btn_basic.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_basicActionPerformed(evt);
            }
        });
        jPanel1.add(btn_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, -1, -1));

        btn_advanced.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CAdvanced.PNG"))); // NOI18N
        btn_advanced.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_advancedActionPerformed(evt);
            }
        });
        jPanel1.add(btn_advanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, -1, -1));

        lbl_basic.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_basic.setForeground(new java.awt.Color(255, 255, 255));
        lbl_basic.setText("Basico");
        jPanel1.add(lbl_basic, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, -1, -1));

        lbl_advanced.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lbl_advanced.setForeground(new java.awt.Color(255, 255, 255));
        lbl_advanced.setText("Avanzado");
        jPanel1.add(lbl_advanced, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 140, 550, 310));

        btn_back.setText("Atras");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, -1, -1));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainback.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        MainView open = new MainView();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void btn_basicActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_basicActionPerformed
        
        CreateBasic open = new CreateBasic();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_basicActionPerformed

    private void btn_advancedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_advancedActionPerformed
        
        JOptionPane.showMessageDialog(null, "Aún no está disponible", "Información", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btn_advancedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Create.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Create().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_advanced;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_basic;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_advanced;
    private javax.swing.JLabel lbl_basic;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
