/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import javax.swing.BoxLayout;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;
import reports.Experience;
import reports.JasperLoader;
import reports.Reference;

/**
 *
 * @author Ronny Trinidad
 */
public class CreateBasic extends javax.swing.JFrame {

    /**
     * Creates new form CreateBasic
     */
    public CreateBasic() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        initPanelExp();
        initPanelRef();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        panel_background = new javax.swing.JPanel();
        panel_base = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_birth = new javax.swing.JLabel();
        lbl_birthplace = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        lbl_nation = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_primary = new javax.swing.JLabel();
        txt_birthplace = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_day = new javax.swing.JTextField();
        lbl_separator = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox<>();
        lbl_month = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        cmb_state = new javax.swing.JComboBox<>();
        txt_nation = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_primary = new javax.swing.JTextField();
        lbl_high = new javax.swing.JLabel();
        txt_high = new javax.swing.JTextField();
        lbl_college = new javax.swing.JLabel();
        txt_college = new javax.swing.JTextField();
        lbl_year = new javax.swing.JLabel();
        txt_career = new javax.swing.JTextField();
        rad_college = new javax.swing.JRadioButton();
        rad_high = new javax.swing.JRadioButton();
        lbl_exp = new javax.swing.JLabel();
        scrollExp = new javax.swing.JScrollPane();
        panel_exp = new javax.swing.JPanel();
        lbl_ref = new javax.swing.JLabel();
        scrollref = new javax.swing.JScrollPane();
        panel_ref = new javax.swing.JPanel();
        btn_addref = new javax.swing.JButton();
        btn_addexp = new javax.swing.JButton();
        btn_save = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        separator_header = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("Atras");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        panel_background.setBackground(new java.awt.Color(1, 0, 73));
        panel_background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_base.setBackground(new java.awt.Color(240, 240, 240));
        panel_base.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name.setText("Nombre Completo");
        panel_base.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_address.setText("Direccion");
        panel_base.add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        panel_base.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        lbl_phone.setText("Numero Telefonico");
        panel_base.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lbl_email.setText("Correo Electronico (opcional)");
        panel_base.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lbl_birth.setText("Fecha de Nacimiento");
        panel_base.add(lbl_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lbl_birthplace.setText("Lugar de Nacimiento");
        panel_base.add(lbl_birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lbl_state.setText("Estado Civil");
        panel_base.add(lbl_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lbl_nation.setText("Nacionalidad");
        panel_base.add(lbl_nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        lbl_cedula.setText("Cedula");
        panel_base.add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lbl_primary.setText("Estudios Primarios");
        panel_base.add(lbl_primary, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        panel_base.add(txt_birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        panel_base.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, -1));
        panel_base.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, -1));
        panel_base.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, -1));

        txt_day.setText("1");
        panel_base.add(txt_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 20, -1));

        lbl_separator.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lbl_separator.setText(":");
        panel_base.add(lbl_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 10, 30));

        cmb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        panel_base.add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        lbl_month.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_month.setText("/");
        panel_base.add(lbl_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        txt_year.setText("1900");
        panel_base.add(txt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, -1));

        cmb_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero.", "Soltera.", "Casado.", "Casada.", "Union Libre." }));
        panel_base.add(cmb_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 160, -1));

        txt_nation.setText("Dominicana");
        panel_base.add(txt_nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, -1));
        panel_base.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 160, -1));
        panel_base.add(txt_primary, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 160, -1));

        lbl_high.setText("Estudios Secundarios");
        panel_base.add(lbl_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        panel_base.add(txt_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        lbl_college.setText("Universidad");
        panel_base.add(lbl_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));
        panel_base.add(txt_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 50, -1));

        lbl_year.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_year.setText(" /");
        panel_base.add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 30, 20));
        panel_base.add(txt_career, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 100, -1));

        rad_college.setText("Si");
        panel_base.add(rad_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 40, 20));

        rad_high.setText("No");
        panel_base.add(rad_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 250, 50, 20));

        lbl_exp.setText("Experiencia Laboral");
        panel_base.add(lbl_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        scrollExp.setBackground(new java.awt.Color(255, 255, 255));

        panel_exp.setBackground(new java.awt.Color(255, 255, 255));
        panel_exp.setLayout(new javax.swing.BoxLayout(panel_exp, javax.swing.BoxLayout.LINE_AXIS));
        scrollExp.setViewportView(panel_exp);

        panel_base.add(scrollExp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 30, 240, 140));

        lbl_ref.setText("Referencia Personal");
        panel_base.add(lbl_ref, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 190, -1, -1));

        panel_ref.setBackground(new java.awt.Color(255, 255, 255));
        panel_ref.setLayout(new javax.swing.BoxLayout(panel_ref, javax.swing.BoxLayout.LINE_AXIS));
        scrollref.setViewportView(panel_ref);

        panel_base.add(scrollref, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 210, 240, 140));

        btn_addref.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_addref.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addrefActionPerformed(evt);
            }
        });
        panel_base.add(btn_addref, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 190, 20, 20));

        btn_addexp.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        btn_addexp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addexpActionPerformed(evt);
            }
        });
        panel_base.add(btn_addexp, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 20, 20));

        panel_background.add(panel_base, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 700, 380));

        btn_save.setText("Guardar e imprimir");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        panel_background.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 410, -1, -1));

        getContentPane().add(panel_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 450));

        title.setFont(new java.awt.Font("Book Antiqua", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Basico");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 74));

        separator_header.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(separator_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 10, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainback.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        Create open = new Create();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        
            // Create the lists for Experience and Reference
            List<Experience> experiences = new ArrayList<>();
            List<Reference> references = new ArrayList<>();
            
            // Create a hashmap with the textFields data
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("name", txt_name.getText());
            parametros.put("address", txt_address.getText());
            parametros.put("birthplace", txt_birthplace.getText());
            parametros.put("state", cmb_state.getSelectedItem());
            parametros.put("nation", txt_nation.getText());
            parametros.put("cedula", txt_cedula.getText());
            parametros.put("primary", txt_primary.getText());
            parametros.put("high", txt_high.getText());
            
            // Add "Cel.: " to the number start
            String phone = txt_phone.getText().trim();
            String finalPhone = "Cel.: " + phone;
            parametros.put("phone", finalPhone);

            // Verify if the email is empty.
            String email = txt_email.getText().trim();
            String finalEmail = email.isEmpty() ? "" : "Email.: " + email;
            parametros.put("email", finalEmail);
            
            // Put the birthday data together
            String day = txt_day.getText().trim();
            String month = (String) cmb_month.getSelectedItem();
            String year = txt_year.getText();
            String finalBirth = day + " de " + month + " de " + year + ".";
            parametros.put("birth", finalBirth);
            
            // Run through experiences
            for (Component comp : panel_exp.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel row = (JPanel) comp;
                    JTextField txt_company = (JTextField) row.getComponent(0);
                    JTextField txt_position = (JTextField) row.getComponent(1);
                    experiences.add(new Experience(txt_company.getText(), txt_position.getText()));
                }
            }

            // Run through 
            for (Component comp : panel_ref.getComponents()) {
                if (comp instanceof JPanel) {
                    JPanel row = (JPanel) comp;
                    JTextField txt_refname = (JTextField) row.getComponent(0);
                    JTextField txt_refphone = (JTextField) row.getComponent(1);
                    references.add(new Reference(txt_refname.getText(), txt_refphone.getText()));
                }
            }
            
            // Show the generated curriculum
            JasperLoader.generarReporte(parametros, experiences, references);
            
    }//GEN-LAST:event_btn_saveActionPerformed

    private void btn_addexpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addexpActionPerformed
        
        addexp();
    }//GEN-LAST:event_btn_addexpActionPerformed

    private void btn_addrefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addrefActionPerformed
        
        addref();
    }//GEN-LAST:event_btn_addrefActionPerformed
    
    private void initPanelExp() {
        panel_exp.setLayout(new BoxLayout(panel_exp, BoxLayout.Y_AXIS));
        scrollExp.setViewportView(panel_exp);
    }
    
    private void initPanelRef() {
        panel_ref.setLayout(new BoxLayout(panel_ref, BoxLayout.Y_AXIS));
        scrollref.setViewportView(panel_ref);
    }
    
    private void addexp() {
        JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
        fila.setBackground(Color.WHITE);
    
        JTextField txt_company = new JTextField("empresa", 15);
        JTextField txt_position = new JTextField("puesto", 15);
        JButton btn_deletexp = new JButton("X");
        
        btn_deletexp.setPreferredSize(new Dimension(43, 20));
        btn_deletexp.setBackground(Color.RED);
        btn_deletexp.setForeground(Color.WHITE);

        btn_deletexp.addActionListener(e -> {
            panel_exp.remove(fila);
            panel_exp.revalidate();
            panel_exp.repaint();
        });

        fila.add(txt_company);
        fila.add(txt_position);
        fila.add(btn_deletexp);

        panel_exp.add(fila);
        panel_exp.revalidate();
        panel_exp.repaint();
    }
    
    private void addref() {
        JPanel fila = new JPanel(new FlowLayout(FlowLayout.LEFT));
        fila.setBackground(Color.WHITE);
    
        JTextField txt_refname = new JTextField("nombre", 15);
        JTextField txt_refphone = new JTextField("telefono", 15);
        JButton btn_deletref = new JButton("X");
        
        btn_deletref.setPreferredSize(new Dimension(43, 20));
        btn_deletref.setBackground(Color.RED);
        btn_deletref.setForeground(Color.WHITE);

        btn_deletref.addActionListener(e -> {
            panel_ref.remove(fila);
            panel_ref.revalidate();
            panel_ref.repaint();
        });

        fila.add(txt_refname);
        fila.add(txt_refphone);
        fila.add(btn_deletref);

        panel_ref.add(fila);
        panel_ref.revalidate();
        panel_ref.repaint();
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBasic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_addexp;
    private javax.swing.JButton btn_addref;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_month;
    private javax.swing.JComboBox<String> cmb_state;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_birth;
    private javax.swing.JLabel lbl_birthplace;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_college;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_exp;
    private javax.swing.JLabel lbl_high;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nation;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_primary;
    private javax.swing.JLabel lbl_ref;
    private javax.swing.JLabel lbl_separator;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JPanel panel_background;
    private javax.swing.JPanel panel_base;
    private javax.swing.JPanel panel_exp;
    private javax.swing.JPanel panel_ref;
    private javax.swing.JRadioButton rad_college;
    private javax.swing.JRadioButton rad_high;
    private javax.swing.JScrollPane scrollExp;
    private javax.swing.JScrollPane scrollref;
    private javax.swing.JSeparator separator_header;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_birthplace;
    private javax.swing.JTextField txt_career;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_college;
    private javax.swing.JTextField txt_day;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_high;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nation;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_primary;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
