/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package views;

import java.util.HashMap;
import java.util.Map;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Ronny Trinidad
 */
public class CreateBasic extends javax.swing.JFrame {

    /**
     * Creates new form CreateBasic
     */
    public CreateBasic() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        compilarReporte();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btn_back = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        lbl_name = new javax.swing.JLabel();
        lbl_address = new javax.swing.JLabel();
        txt_address = new javax.swing.JTextField();
        lbl_phone = new javax.swing.JLabel();
        lbl_email = new javax.swing.JLabel();
        lbl_birth = new javax.swing.JLabel();
        lbl_birthplace = new javax.swing.JLabel();
        lbl_state = new javax.swing.JLabel();
        lbl_nation = new javax.swing.JLabel();
        lbl_cedula = new javax.swing.JLabel();
        lbl_primary = new javax.swing.JLabel();
        txt_birthplace = new javax.swing.JTextField();
        txt_name = new javax.swing.JTextField();
        txt_phone = new javax.swing.JTextField();
        txt_email = new javax.swing.JTextField();
        txt_day = new javax.swing.JTextField();
        lbl_separator = new javax.swing.JLabel();
        cmb_month = new javax.swing.JComboBox<>();
        lbl_month = new javax.swing.JLabel();
        txt_year = new javax.swing.JTextField();
        cmb_state = new javax.swing.JComboBox<>();
        txt_nation = new javax.swing.JTextField();
        txt_cedula = new javax.swing.JTextField();
        txt_primary = new javax.swing.JTextField();
        lbl_high = new javax.swing.JLabel();
        txt_high = new javax.swing.JTextField();
        lbl_college = new javax.swing.JLabel();
        txt_college = new javax.swing.JTextField();
        lbl_year = new javax.swing.JLabel();
        txt_career = new javax.swing.JTextField();
        rad_college = new javax.swing.JRadioButton();
        rad_high = new javax.swing.JRadioButton();
        lbl_exp = new javax.swing.JLabel();
        btn_save = new javax.swing.JButton();
        title = new javax.swing.JLabel();
        separator_header = new javax.swing.JSeparator();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_back.setText("Atras");
        btn_back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_backActionPerformed(evt);
            }
        });
        getContentPane().add(btn_back, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        jPanel1.setBackground(new java.awt.Color(1, 0, 73));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane1.setHorizontalScrollBar(null);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl_name.setText("Nombre Completo");
        jPanel2.add(lbl_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));

        lbl_address.setText("Direccion");
        jPanel2.add(lbl_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));
        jPanel2.add(txt_address, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 180, -1));

        lbl_phone.setText("Numero Telefonico");
        jPanel2.add(lbl_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, -1, -1));

        lbl_email.setText("Correo Electronico (opcional)");
        jPanel2.add(lbl_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, -1, -1));

        lbl_birth.setText("Fecha de Nacimiento");
        jPanel2.add(lbl_birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));

        lbl_birthplace.setText("Lugar de Nacimiento");
        jPanel2.add(lbl_birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, -1, -1));

        lbl_state.setText("Estado Civil");
        jPanel2.add(lbl_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, -1, -1));

        lbl_nation.setText("Nacionalidad");
        jPanel2.add(lbl_nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 70, -1, -1));

        lbl_cedula.setText("Cedula");
        jPanel2.add(lbl_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, -1, -1));

        lbl_primary.setText("Estudios Primarios");
        jPanel2.add(lbl_primary, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 190, -1, -1));
        jPanel2.add(txt_birthplace, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 180, -1));

        txt_name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_nameActionPerformed(evt);
            }
        });
        jPanel2.add(txt_name, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 180, -1));
        jPanel2.add(txt_phone, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 180, -1));
        jPanel2.add(txt_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 180, -1));

        txt_day.setText("1");
        jPanel2.add(txt_day, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 20, -1));

        lbl_separator.setFont(new java.awt.Font("Segoe UI", 0, 22)); // NOI18N
        lbl_separator.setText(":");
        jPanel2.add(lbl_separator, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, 10, 30));

        cmb_month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));
        jPanel2.add(cmb_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 20));

        lbl_month.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_month.setText("/");
        jPanel2.add(lbl_month, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 270, -1, 20));

        txt_year.setText("1900");
        jPanel2.add(txt_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 40, -1));

        cmb_state.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Soltero", "Soltera", "Casado", "Casada", "Union Libre" }));
        jPanel2.add(cmb_state, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 30, 160, -1));

        txt_nation.setText("Dominicana");
        jPanel2.add(txt_nation, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 90, 160, -1));
        jPanel2.add(txt_cedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 150, 160, -1));
        jPanel2.add(txt_primary, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 160, -1));

        lbl_high.setText("Estudios Secundarios");
        jPanel2.add(lbl_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, -1, -1));
        jPanel2.add(txt_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 270, 160, -1));

        lbl_college.setText("Universidad");
        jPanel2.add(lbl_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, -1, -1));
        jPanel2.add(txt_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 330, 50, -1));

        lbl_year.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        lbl_year.setText(" /");
        jPanel2.add(lbl_year, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, 30, 20));
        jPanel2.add(txt_career, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 100, -1));

        rad_college.setText("Si");
        jPanel2.add(rad_college, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 40, 20));

        rad_high.setText("Si");
        jPanel2.add(rad_high, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 250, 40, 20));

        lbl_exp.setText("Experiencia Laboral");
        jPanel2.add(lbl_exp, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 10, -1, -1));

        jScrollPane1.setViewportView(jPanel2);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 20, 700, 380));

        btn_save.setText("Guardar e imprimir");
        btn_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_saveActionPerformed(evt);
            }
        });
        jPanel1.add(btn_save, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 410, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 70, 910, 450));

        title.setFont(new java.awt.Font("Book Antiqua", 3, 48)); // NOI18N
        title.setForeground(new java.awt.Color(255, 255, 255));
        title.setText("Basico");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 0, 150, 74));

        separator_header.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(separator_header, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 10, 50));

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/mainback.jpg"))); // NOI18N
        getContentPane().add(background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 520));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_backActionPerformed

        Create open = new Create();
        open.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btn_backActionPerformed

    private void txt_nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_nameActionPerformed

    private void btn_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_saveActionPerformed
        // TODO add your handling code here:
        
        generarReporte();
    }//GEN-LAST:event_btn_saveActionPerformed

    public void compilarReporte() {
        try {
            // .jrxml file route
            String jrxmlPath = "/reports/Basic.jrxml";
            // compile jrxml to jasper
            JasperCompileManager.compileReportToFile(jrxmlPath, "/reports/Basic.jasper");
            JOptionPane.showMessageDialog(this, "Reporte compilado con éxito", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } catch (JRException e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al compilar el reporte", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    public void generarReporte() {
        try {
            // 1. .jasper file route
            String reportePath = "src/reports/Curriculum.jasper";
            JasperReport reporte = (JasperReport) JRLoader.loadObjectFromFile(reportePath);

            // 2. create a hashmap with the textFields data
            Map<String, Object> parametros = new HashMap<>();
            parametros.put("name", txt_name.getText());
            parametros.put("address", txt_address.getText());
            parametros.put("birthplace", txt_birthplace.getText());
            parametros.put("state", cmb_state.getSelectedItem());
            parametros.put("nation", txt_nation.getText());
            parametros.put("cedula", txt_cedula.getText());
            parametros.put("primary", txt_primary.getText());
            parametros.put("high", txt_high.getText());
            
            // Add "Cel.: " to the number start
            String phone = txt_phone.getText().trim();
            String finalPhone = "Cel.: " + phone;
            parametros.put("phone", finalPhone);

            // Verify if the email is empty.
            String email = txt_email.getText().trim();
            String finalEmail = email.isEmpty() ? "" : "Email.: " + email;
            parametros.put("email", finalEmail);
            
            // Put the birthday data together
            String day = txt_day.getText().trim();
            String month = (String) cmb_month.getSelectedItem();
            String year = txt_year.getText();
            String finalBirth = day + " de " + month + " de " + year + ".";
            parametros.put("birth", finalBirth);

            // 3. fill the report with the hashmap
            JasperPrint print = JasperFillManager.fillReport(reporte, parametros, new JREmptyDataSource());

            // 4. show the report
            JasperViewer.viewReport(print, false);

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Error al generar el reporte", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    
    
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateBasic.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateBasic().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton btn_back;
    private javax.swing.JButton btn_save;
    private javax.swing.JComboBox<String> cmb_month;
    private javax.swing.JComboBox<String> cmb_state;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbl_address;
    private javax.swing.JLabel lbl_birth;
    private javax.swing.JLabel lbl_birthplace;
    private javax.swing.JLabel lbl_cedula;
    private javax.swing.JLabel lbl_college;
    private javax.swing.JLabel lbl_email;
    private javax.swing.JLabel lbl_exp;
    private javax.swing.JLabel lbl_high;
    private javax.swing.JLabel lbl_month;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_nation;
    private javax.swing.JLabel lbl_phone;
    private javax.swing.JLabel lbl_primary;
    private javax.swing.JLabel lbl_separator;
    private javax.swing.JLabel lbl_state;
    private javax.swing.JLabel lbl_year;
    private javax.swing.JRadioButton rad_college;
    private javax.swing.JRadioButton rad_high;
    private javax.swing.JSeparator separator_header;
    private javax.swing.JLabel title;
    private javax.swing.JTextField txt_address;
    private javax.swing.JTextField txt_birthplace;
    private javax.swing.JTextField txt_career;
    private javax.swing.JTextField txt_cedula;
    private javax.swing.JTextField txt_college;
    private javax.swing.JTextField txt_day;
    private javax.swing.JTextField txt_email;
    private javax.swing.JTextField txt_high;
    private javax.swing.JTextField txt_name;
    private javax.swing.JTextField txt_nation;
    private javax.swing.JTextField txt_phone;
    private javax.swing.JTextField txt_primary;
    private javax.swing.JTextField txt_year;
    // End of variables declaration//GEN-END:variables
}
